defaults: &defaults
  access_key_id: 'AKIAII3PGZXSFC3Q2S7Q'
  secret_access_key: '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'
  region: 'Sydney'
development:
  <<: *defaults
  bucket: 'little-caesars-dev'
test:
  <<: *defaults
  bucket: 'little-caesars-test'
production:
  <<: *defaults
  bucket: 'little-caesars-prod'